//Profile data
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

//Authentication
export const USER_AUTH = 'USER_AUTH';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILED = 'USER_AUTH_FAILED';
export const GET_AUTHENTICATED_USER = 'GET_AUTHENTICATED_USER';
export const GET_AUTHENTICATED_USER_SUCCESS = 'GET_AUTHENTICATED_USER_SUCCESS';
export const GET_AUTHENTICATED_USER_FAILED = 'GET_AUTHENTICATED_USER_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

//Register
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

//User's actions

//Education (omg this is going to be huge 😫)
export const CREATE_EDUCATION = 'CREATE_EDUCATION';
export const CREATE_EDUCATION_SUCCESS = 'CREATE_EDUCATION_SUCCESS';
export const CREATE_EDUCATION_FAILED = 'CREATE_EDUCATION_FAILED';
export const EDIT_EDUCATION = 'EDIT_EDUCATION';
export const EDIT_EDUCATION_SUCCESS = 'EDIT_EDUCATION_SUCCESS';
export const EDIT_EDUCATION_FAILED = 'EDIT_EDUCATION_FAILED';
export const DELETE_EDUCATION = 'DELETE_EDUCATION';
export const DELETE_EDUCATION_SUCCESS = 'DELETE_EDUCATION_SUCCESS';
export const DELETE_EDUCATION_FAILED = 'DELETE_EDUCATION_FAILED';

//Jobs
export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILED = 'CREATE_JOB_FAILED';
export const EDIT_JOB = 'EDIT_JOB';
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';
export const EDIT_JOB_FAILED = 'EDIT_JOB_FAILED';
export const DELETE_JOB = 'DELETE_JOB';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';
export const DELETE_JOB_FAILED = 'DELETE_JOB_FAILED';

//Courses
export const CREATE_COURSE = 'CREATE_COURSE';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILED = 'CREATE_COURSE_FAILED';
export const EDIT_COURSE = 'EDIT_COURSE';
export const EDIT_COURSE_SUCCESS = 'EDIT_COURSE_SUCCESS';
export const EDIT_COURSE_FAILED = 'EDIT_COURSE_FAILED';
export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAILED = 'DELETE_COURSE_FAILED';

//Skills
export const CREATE_SKILL = 'CREATE_SKILL';
export const CREATE_SKILL_SUCCESS = 'CREATE_SKILL_SUCCESS';
export const CREATE_SKILL_FAILED = 'CREATE_SKILL_FAILED';
export const EDIT_SKILL = 'EDIT_SKILL';
export const EDIT_SKILL_SUCCESS = 'EDIT_SKILL_SUCCESS';
export const EDIT_SKILL_FAILED = 'EDIT_SKILL_FAILED';
export const DELETE_SKILL = 'DELETE_SKILL';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';
export const DELETE_SKILL_FAILED = 'DELETE_SKILL_FAILED';