//Profile data
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

//Users actions
export const USER_AUTH = 'USER_AUTH';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILED = 'USER_AUTH_FAILED';
export const GET_AUTHENTICATED_USER = 'GET_AUTHENTICATED_USER';
export const GET_AUTHENTICATED_USER_SUCCESS = 'GET_AUTHENTICATED_USER_SUCCESS';
export const GET_AUTHENTICATED_USER_FAILED = 'GET_AUTHENTICATED_USER_FAILED';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';